name: Deploy Angular a IONOS

on:
  push:
    branches:
      - main  # Asegúrate de que tu rama principal se llame main o cambia esto a master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # O la versión que estés usando localmente

      - name: Instalar dependencias
        run: npm install

      - name: Hacer Build de producción
        run: npm run build 

      - name: Subir a IONOS vía SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: access-5019987479.webspace-host.com
          username: su140534
          password: ${{ secrets.FTP_PASSWORD }} # La contraseña la pones en GitHub Secrets
          port: 22
          # Ajustamos la ruta local basada en lo que me mostraste
          # Subimos el contenido de 'browser' que es donde está el index.html final
          local-dir: ./dist/web-congreso-geologia/browser/
          server-dir: ./dist/ 
          protocol: sftp